-- Dulac My Camp — core schema.
-- Single-property app: no tenant scoping, no RLS. Every table is global.

-- Guests and admins. A row is created on first OTP request (self-registration).
CREATE TABLE users (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    email         text NOT NULL UNIQUE,
    full_name     text,
    phone         text,
    relationship  text,                      -- "cousin", "friend of Marc", ...
    boat_info     text,                      -- length, draft, trailer needs
    notes         text,
    role          text NOT NULL DEFAULT 'guest',   -- 'guest' | 'admin'
    avatar_url    text,
    last_login_at timestamptz,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT users_role_valid CHECK (role IN ('guest', 'admin'))
);

-- Short-lived one-time passcodes for passwordless login.
CREATE TABLE otp_codes (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    email      text NOT NULL,
    code       text NOT NULL,
    expires_at timestamptz NOT NULL,
    used       boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- Stay requests. Overlaps are permitted on purpose — the owner arbitrates.
CREATE TABLE bookings (
    id                       uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id                  uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    check_in                 date NOT NULL,
    check_out                date NOT NULL,
    guest_count_adults       integer NOT NULL DEFAULT 1,
    guest_count_kids         integer NOT NULL DEFAULT 0,
    has_pets                 boolean NOT NULL DEFAULT false,
    other_requests           text,
    status                   text NOT NULL DEFAULT 'pending',
                             -- 'pending' | 'approved' | 'denied' | 'cancelled'
    denied_reason            text,
    approved_at              timestamptz,
    approved_by              text,           -- 'owner' | 'admin' | email
    approve_token            text UNIQUE,    -- single-use, one-click email approval
    approve_token_expires_at timestamptz,
    created_at               timestamptz NOT NULL DEFAULT now(),
    updated_at               timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT valid_dates    CHECK (check_out > check_in),
    CONSTRAINT valid_adults   CHECK (guest_count_adults > 0),
    CONSTRAINT valid_kids     CHECK (guest_count_kids >= 0),
    CONSTRAINT bookings_status_valid
        CHECK (status IN ('pending', 'approved', 'denied', 'cancelled'))
);

-- Ranges the camp is unavailable. Inclusive on both ends.
CREATE TABLE blackout_dates (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    start_date date NOT NULL,
    end_date   date NOT NULL,
    reason     text,
    created_by uuid REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT valid_blackout CHECK (end_date >= start_date)
);

-- Rodeos, tournaments, holidays — annotations on the calendar, not blockers.
CREATE TABLE special_events (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name        text NOT NULL,
    event_date  date NOT NULL,
    end_date    date,
    description text,
    emoji       text DEFAULT '🎉',
    created_by  uuid REFERENCES users(id) ON DELETE SET NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT valid_event_range CHECK (end_date IS NULL OR end_date >= event_date)
);

-- In-app inbox. sender_id NULL means the message was generated by the system.
CREATE TABLE messages (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    sender_id    uuid REFERENCES users(id) ON DELETE SET NULL,
    recipient_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    subject      text,
    body         text NOT NULL,
    is_read      boolean NOT NULL DEFAULT false,
    booking_id   uuid REFERENCES bookings(id) ON DELETE SET NULL,
    created_at   timestamptz NOT NULL DEFAULT now()
);

INSERT INTO users (email, full_name, role)
VALUES ('marc@recoresystems.net', 'Marc Dugas', 'admin')
ON CONFLICT (email) DO NOTHING;
